// Comprehensive Zerava Language Vocabulary (350+ words)
const zeravaVocabulary = {
  // Pronouns (20 words)
  "𐔀𐔋": { bengali: "আমি", category: "pronouns", english: "I/me" },
  "𐔎𐔂": { bengali: "তুমি", category: "pronouns", english: "you (informal)" },
  "𐔋𐔄𐔑": { bengali: "সে", category: "pronouns", english: "he/she" },
  "𐔐𐔑𐔒": { bengali: "আমি নিজেই", category: "pronouns", english: "myself" },
  "𐔑𐔒𐔂": { bengali: "তোমরা সবাই", category: "pronouns", english: "all of you" },
  "𐔒𐔓𐔂": { bengali: "তারা সবাই", category: "pronouns", english: "all of them" },
  "𐔑𐔑𐔂": { bengali: "আমরা", category: "pronouns", english: "we" },
  "𐔒𐔓𐔑": { bengali: "তোমরা", category: "pronouns", english: "you (plural)" },
  "𐔓𐔒𐔑": { bengali: "তারা", category: "pronouns", english: "they" },
  "𐔔𐔒𐔑": { bengali: "নিজস্ব", category: "pronouns", english: "own/self" },
  "𐔀𐔂𐔋": { bengali: "আমার", category: "pronouns", english: "my/mine" },
  "𐔎𐔂𐔋": { bengali: "তোমার", category: "pronouns", english: "your" },
  "𐔋𐔂𐔋": { bengali: "তার", category: "pronouns", english: "his/her" },
  "𐔍𐔂𐔋": { bengali: "আমাদের", category: "pronouns", english: "our" },
  "𐔏𐔂𐔋": { bengali: "তোমাদের", category: "pronouns", english: "your (plural)" },
  "𐔐𐔂𐔋": { bengali: "তাদের", category: "pronouns", english: "their" },
  "𐔑𐔂𐔋": { bengali: "কে", category: "pronouns", english: "who" },
  "𐔒𐔂𐔋": { bengali: "কি", category: "pronouns", english: "what" },
  "𐔓𐔂𐔋": { bengali: "কোথায়", category: "pronouns", english: "where" },
  "𐔔𐔂𐔋": { bengali: "কখন", category: "pronouns", english: "when" },

  // Verbs (50 words)
  "𐔍𐔉": { bengali: "খাওয়া", category: "verbs", english: "to eat" },
  "𐔏𐔂": { bengali: "দেখা", category: "verbs", english: "to see" },
  "𐔑𐔄": { bengali: "আসা", category: "verbs", english: "to come" },
  "𐔍𐔂": { bengali: "যাওয়া", category: "verbs", english: "to go" },
  "𐔎𐔉": { bengali: "বলা", category: "verbs", english: "to say" },
  "𐔑𐔄𐔒": { bengali: "দেখানো", category: "verbs", english: "to show" },
  "𐔍𐔉𐔂": { bengali: "খাওয়ানো", category: "verbs", english: "to feed" },
  "𐔏𐔂𐔓": { bengali: "শোনানো", category: "verbs", english: "to tell/narrate" },
  "𐔎𐔂𐔑": { bengali: "বলানো", category: "verbs", english: "to make say" },
  "𐔋𐔄𐔒": { bengali: "লিখানো", category: "verbs", english: "to make write" },
  "𐔐𐔄𐔂": { bengali: "নাচানো", category: "verbs", english: "to make dance" },
  "𐔑𐔑𐔂": { bengali: "দৌড়ানো", category: "verbs", english: "to make run" },
  "𐔒𐔑𐔂": { bengali: "চাপানো", category: "verbs", english: "to press" },
  "𐔑𐔂𐔉": { bengali: "পড়া", category: "verbs", english: "to read" },
  "𐔎𐔑𐔂": { bengali: "লিখা", category: "verbs", english: "to write" },
  "𐔋𐔂𐔎": { bengali: "নাচা", category: "verbs", english: "to dance" },
  "𐔍𐔂𐔏": { bengali: "গাওয়া", category: "verbs", english: "to sing" },
  "𐔏𐔂𐔐": { bengali: "দৌড়ানো", category: "verbs", english: "to run" },
  "𐔐𐔂𐔑": { bengali: "শোনানো", category: "verbs", english: "to listen" },
  "𐔑𐔂𐔌": { bengali: "ছোঁয়া", category: "verbs", english: "to touch" },
  "𐔒𐔂𐔏": { bengali: "ধরা", category: "verbs", english: "to catch" },
  "𐔓𐔂𐔑": { bengali: "খেলা", category: "verbs", english: "to play" },
  "𐔔𐔂𐔎": { bengali: "চলাচল করা", category: "verbs", english: "to move" },
  "𐔀𐔉𐔂": { bengali: "ঘুমানো", category: "verbs", english: "to sleep" },
  "𐔎𐔉𐔂": { bengali: "উঠা", category: "verbs", english: "to get up" },
  "𐔋𐔉𐔂": { bengali: "বসা", category: "verbs", english: "to sit" },
  "𐔍𐔉𐔂": { bengali: "দাঁড়ানো", category: "verbs", english: "to stand" },
  "𐔏𐔉𐔂": { bengali: "হাঁটা", category: "verbs", english: "to walk" },
  "𐔐𐔉𐔂": { bengali: "কাজ করা", category: "verbs", english: "to work" },
  "𐔑𐔉𐔂": { bengali: "রান্na করা", category: "verbs", english: "to cook" },
  "𐔒𐔉𐔂": { bengali: "পরিষ্কার করা", category: "verbs", english: "to clean" },
  "𐔓𐔉𐔂": { bengali: "কিনা", category: "verbs", english: "to buy" },
  "𐔔𐔉𐔂": { bengali: "বিক্রি করা", category: "verbs", english: "to sell" },
  "𐔀𐔏𐔂": { bengali: "পছন্দ করা", category: "verbs", english: "to like" },
  "𐔎𐔏𐔂": { bengali: "ভালোবাসা", category: "verbs", english: "to love" },
  "𐔋𐔏𐔂": { bengali: "ঘৃণা করা", category: "verbs", english: "to hate" },
  "𐔍𐔏𐔂": { bengali: "চাওয়া", category: "verbs", english: "to want" },
  "𐔏𐔏𐔂": { bengali: "প্রয়োজন", category: "verbs", english: "to need" },
  "𐔐𐔏𐔂": { bengali: "সাহায্য করা", category: "verbs", english: "to help" },
  "𐔑𐔏𐔂": { bengali: "শেখা", category: "verbs", english: "to learn" },
  "𐔒𐔏𐔂": { bengali: "শেখানো", category: "verbs", english: "to teach" },
  "𐔓𐔏𐔂": { bengali: "জানা", category: "verbs", english: "to know" },
  "𐔔𐔏𐔂": { bengali: "মনে রাখা", category: "verbs", english: "to remember" },
  "𐔀𐔐𐔂": { bengali: "ভুলে যাওয়া", category: "verbs", english: "to forget" },
  "𐔎𐔐𐔂": { bengali: "চিন্তা করা", category: "verbs", english: "to think" },
  "𐔋𐔐𐔂": { bengali: "বোঝা", category: "verbs", english: "to understand" },
  "𐔍𐔐𐔂": { bengali: "বিশ্বাস করা", category: "verbs", english: "to believe" },
  "𐔏𐔐𐔂": { bengali: "আশা করা", category: "verbs", english: "to hope" },
  "𐔐𐔐𐔂": { bengali: "স্বপ্ন দেখা", category: "verbs", english: "to dream" },
  "𐔑𐔐𐔂": { bengali: "হাসা", category: "verbs", english: "to laugh" },
  "𐔒𐔐𐔂": { bengali: "কাঁদা", category: "verbs", english: "to cry" },

  // Objects/Nouns (80 words)
  "𐔉𐔂𐔋": { bengali: "ভাত", category: "nouns", english: "rice" },
  "𐔄𐔑": { bengali: "ঘর", category: "nouns", english: "house" },
  "𐔎𐔂𐔓": { bengali: "আলো", category: "nouns", english: "light" },
  "𐔊𐔃": { bengali: "জল", category: "nouns", english: "water" },
  "𐔆𐔃𐔐": { bengali: "সূর্য", category: "nouns", english: "sun" },
  "𐔓𐔑𐔎": { bengali: "ছাতা", category: "nouns", english: "umbrella" },
  "𐔔𐔑𐔎": { bengali: "গ্লাস", category: "nouns", english: "glass" },
  "𐔀𐔑𐔎": { bengali: "খেলা", category: "nouns", english: "game" },
  "𐔎𐔑𐔐": { bengali: "বাগান", category: "nouns", english: "garden" },
  "𐔋𐔑𐔐": { bengali: "ফলমূল", category: "nouns", english: "fruits" },
  "𐔍𐔑𐔐": { bengali: "পাহাড়ি পথ", category: "nouns", english: "mountain path" },
  "𐔏𐔑𐔐": { bengali: "নদীর ধারা", category: "nouns", english: "river flow" },
  "𐔐𐔑𐔏": { bengali: "বাজার", category: "nouns", english: "market" },
  "𐔑𐔑𐔏": { bengali: "সন্ধ্যা", category: "nouns", english: "evening" },
  "𐔒𐔑𐔏": { bengali: "প্রভাত", category: "nouns", english: "dawn" },
  "𐔀𐔃": { bengali: "পাতা", category: "nouns", english: "leaf" },
  "𐔎𐔃": { bengali: "ফুল", category: "nouns", english: "flower" },
  "𐔋𐔃": { bengali: "ফল", category: "nouns", english: "fruit" },
  "𐔍𐔃": { bengali: "গাছ", category: "nouns", english: "tree" },
  "𐔏𐔃": { bengali: "পাহাড়", category: "nouns", english: "mountain" },
  "𐔐𐔃": { bengali: "নদী", category: "nouns", english: "river" },
  "𐔑𐔃": { bengali: "সমুদ্র", category: "nouns", english: "sea" },
  "𐔒𐔃": { bengali: "মেঘ", category: "nouns", english: "cloud" },
  "𐔓𐔃": { bengali: "বৃষ্টি", category: "nouns", english: "rain" },
  "𐔔𐔃": { bengali: "বাতাস", category: "nouns", english: "wind" },
  "𐔀𐔄": { bengali: "চাঁদ", category: "nouns", english: "moon" },
  "𐔎𐔄": { bengali: "তারকা", category: "nouns", english: "star" },
  "𐔋𐔄": { bengali: "আকাশ", category: "nouns", english: "sky" },
  "𐔍𐔄": { bengali: "পৃথিবী", category: "nouns", english: "earth" },
  "𐔏𐔄": { bengali: "মাটি", category: "nouns", english: "soil" },
  "𐔀𐔐𐔀": { bengali: "বই", category: "nouns", english: "book" },
  "𐔎𐔐𐔀": { bengali: "কলম", category: "nouns", english: "pen" },
  "𐔋𐔐𐔀": { bengali: "কাগজ", category: "nouns", english: "paper" },
  "𐔍𐔐𐔀": { bengali: "ঘড়ি", category: "nouns", english: "watch/clock" },
  "𐔏𐔐𐔀": { bengali: "পেন", category: "nouns", english: "pen" },
  "𐔐𐔐𐔀": { bengali: "ডায়েরি", category: "nouns", english: "diary" },
  "𐔑𐔐𐔀": { bengali: "কম্পাস", category: "nouns", english: "compass" },
  "𐔒𐔐𐔀": { bengali: "ফ্লাস্ক", category: "nouns", english: "flask" },
  "𐔓𐔐𐔀": { bengali: "টেবিল", category: "nouns", english: "table" },
  "𐔔𐔐𐔀": { bengali: "চেয়ার", category: "nouns", english: "chair" },
  "𐔀𐔓": { bengali: "চাবি", category: "miscellaneous", english: "key" },
  "𐔎𐔓": { bengali: "ফুলদানি", category: "miscellaneous", english: "vase" },
  "𐔋𐔓": { bengali: "ট্রলি", category: "miscellaneous", english: "trolley" },
  "𐔍𐔓": { bengali: "মাথা ঘড়ি", category: "miscellaneous", english: "headwatch" },
  "𐔏𐔓": { bengali: "ছবি ফ্রেম", category: "miscellaneous", english: "photo frame" },
  "𐔐𐔓": { bengali: "দরজার হ্যান্ডেল", category: "miscellaneous", english: "door handle" },
  "𐔑𐔓": { bengali: "পাত্র", category: "miscellaneous", english: "container" },
  "𐔒𐔓": { bengali: "ব্যালান্স", category: "miscellaneous", english: "balance" },
  "𐔓𐔓": { bengali: "ফ্রিজ", category: "miscellaneous", english: "fridge" },
  "𐔔𐔓": { bengali: "চশমা", category: "miscellaneous", english: "glasses" },
  "𐔀𐔑𐔉": { bengali: "রুটি", category: "nouns", english: "bread" },
  "𐔎𐔑𐔉": { bengali: "মাছ", category: "nouns", english: "fish" },
  "𐔋𐔑𐔉": { bengali: "মাংস", category: "nouns", english: "meat" },
  "𐔍𐔑𐔉": { bengali: "তরকারি", category: "nouns", english: "vegetable" },
  "𐔏𐔑𐔉": { bengali: "দুধ", category: "nouns", english: "milk" },
  "𐔐𐔑𐔉": { bengali: "চা", category: "nouns", english: "tea" },
  "𐔑𐔑𐔉": { bengali: "কফি", category: "nouns", english: "coffee" },
  "𐔒𐔑𐔉": { bengali: "চিনি", category: "nouns", english: "sugar" },
  "𐔓𐔑𐔉": { bengali: "লবণ", category: "nouns", english: "salt" },
  "𐔔𐔑𐔉": { bengali: "তেল", category: "nouns", english: "oil" },
  "𐔀𐔒𐔉": { bengali: "জামা", category: "nouns", english: "shirt" },
  "𐔎𐔒𐔉": { bengali: "প্যান্ট", category: "nouns", english: "pants" },
  "𐔋𐔒𐔉": { bengali: "জুতা", category: "nouns", english: "shoes" },
  "𐔍𐔒𐔉": { bengali: "টুপি", category: "nouns", english: "hat" },
  "𐔏𐔒𐔉": { bengali: "ব্যাগ", category: "nouns", english: "bag" },
  "𐔐𐔒𐔉": { bengali: "মোবাইল", category: "nouns", english: "mobile" },
  "𐔑𐔒𐔉": { bengali: "কম্পিউটার", category: "nouns", english: "computer" },
  "𐔒𐔒𐔉": { bengali: "টেলিভিশন", category: "nouns", english: "television" },
  "𐔓𐔒𐔉": { bengali: "রেডিও", category: "nouns", english: "radio" },
  "𐔔𐔒𐔉": { bengali: "গাড়ি", category: "nouns", english: "car" },
  "𐔀𐔓𐔉": { bengali: "বাস", category: "nouns", english: "bus" },
  "𐔎𐔓𐔉": { bengali: "ট্রেন", category: "nouns", english: "train" },
  "𐔋𐔓𐔉": { bengali: "প্লেন", category: "nouns", english: "plane" },
  "𐔍𐔓𐔉": { bengali: "নৌকা", category: "nouns", english: "boat" },
  "𐔏𐔓𐔉": { bengali: "সাইকেল", category: "nouns", english: "bicycle" },
  "𐔐𐔓𐔉": { bengali: "রিকশা", category: "nouns", english: "rickshaw" },
  "𐔑𐔓𐔉": { bengali: "দোকান", category: "nouns", english: "shop" },
  "𐔒𐔓𐔉": { bengali: "হাসপাতাল", category: "nouns", english: "hospital" },
  "𐔓𐔓𐔉": { bengali: "স্কুল", category: "nouns", english: "school" },
  "𐔔𐔓𐔉": { bengali: "বিশ্ববিদ্যালয়", category: "nouns", english: "university" },
  "𐔀𐔔𐔉": { bengali: "অফিস", category: "nouns", english: "office" },
  "𐔎𐔔𐔉": { bengali: "ব্যাংক", category: "nouns", english: "bank" },
  "𐔋𐔔𐔉": { bengali: "পোস্ট অফিস", category: "nouns", english: "post office" },
  "𐔍𐔔𐔉": { bengali: "রেস্তোরাঁ", category: "nouns", english: "restaurant" },

  // Colors (15 words)
  "𐔒𐔄𐔂": { bengali: "কমলা", category: "colors", english: "orange" },
  "𐔓𐔄𐔂": { bengali: "গোলাপি", category: "colors", english: "pink" },
  "𐔔𐔄𐔂": { bengali: "বাদামী", category: "colors", english: "brown" },
  "𐔀𐔄𐔂": { bengali: "ধূসর", category: "colors", english: "gray" },
  "𐔎𐔄𐔂": { bengali: "নীলাভ", category: "colors", english: "bluish" },
  "𐔋𐔄𐔂": { bengali: "সবুজাভ", category: "colors", english: "greenish" },
  "𐔑𐔄": { bengali: "লাল", category: "colors", english: "red" },
  "𐔒𐔄": { bengali: "হলুদ", category: "colors", english: "yellow" },
  "𐔓𐔄": { bengali: "সাদা", category: "colors", english: "white" },
  "𐔔𐔄": { bengali: "কালো", category: "colors", english: "black" },
  "𐔀𐔄": { bengali: "সবুজ", category: "colors", english: "green" },
  "𐔎𐔄": { bengali: "নীল", category: "colors", english: "blue" },
  "𐔋𐔄": { bengali: "গোলাপি", category: "colors", english: "pink" },
  "𐔍𐔄": { bengali: "বেগুনি", category: "colors", english: "purple" },
  "𐔏𐔄": { bengali: "রূপালি", category: "colors", english: "silver" },

  // Numbers (30 words)
  "𐔀𐔀": { bengali: "১", category: "numbers", english: "1" },
  "𐔁𐔀": { bengali: "২", category: "numbers", english: "2" },
  "𐔂𐔀": { bengali: "৩", category: "numbers", english: "3" },
  "𐔃𐔀": { bengali: "৪", category: "numbers", english: "4" },
  "𐔄𐔀": { bengali: "৫", category: "numbers", english: "5" },
  "𐔅𐔀": { bengali: "৬", category: "numbers", english: "6" },
  "𐔆𐔀": { bengali: "৭", category: "numbers", english: "7" },
  "𐔇𐔀": { bengali: "৮", category: "numbers", english: "8" },
  "𐔈𐔀": { bengali: "৯", category: "numbers", english: "9" },
  "𐔉𐔀": { bengali: "১০", category: "numbers", english: "10" },
  "𐔊𐔀": { bengali: "১১", category: "numbers", english: "11" },
  "𐔋𐔀": { bengali: "১২", category: "numbers", english: "12" },
  "𐔌𐔀": { bengali: "১৩", category: "numbers", english: "13" },
  "𐔏𐔀": { bengali: "১৪", category: "numbers", english: "14" },
  "𐔐𐔀": { bengali: "১৫", category: "numbers", english: "15" },
  "𐔑𐔀": { bengali: "১৬", category: "numbers", english: "16" },
  "𐔒𐔀": { bengali: "১৭", category: "numbers", english: "17" },
  "𐔓𐔀": { bengali: "১৮", category: "numbers", english: "18" },
  "𐔔𐔀": { bengali: "১৯", category: "numbers", english: "19" },
  "𐔀𐔁": { bengali: "২০", category: "numbers", english: "20" },
  "𐔀𐔂": { bengali: "৩০", category: "numbers", english: "30" },
  "𐔀𐔃": { bengali: "৪০", category: "numbers", english: "40" },
  "𐔀𐔄": { bengali: "৫০", category: "numbers", english: "50" },
  "𐔀𐔅": { bengali: "৬০", category: "numbers", english: "60" },
  "𐔀𐔆": { bengali: "৭০", category: "numbers", english: "70" },
  "𐔀𐔇": { bengali: "৮০", category: "numbers", english: "80" },
  "𐔀𐔈": { bengali: "৯০", category: "numbers", english: "90" },
  "𐔁𐔁": { bengali: "১০০", category: "numbers", english: "100" },
  "𐔂𐔁": { bengali: "১০০০", category: "numbers", english: "1000" },
  "𐔃𐔁": { bengali: "শূন্য", category: "numbers", english: "zero" },

  // Animals (25 words)
  "𐔀𐔑": { bengali: "কুকুর", category: "animals", english: "dog" },
  "𐔎𐔑": { bengali: "বিড়াল", category: "animals", english: "cat" },
  "𐔋𐔑": { bengali: "হরিণ", category: "animals", english: "deer" },
  "𐔍𐔑": { bengali: "গরু", category: "animals", english: "cow" },
  "𐔏𐔑": { bengali: "ঘোড়া", category: "animals", english: "horse" },
  "𐔐𐔑": { bengali: "মোষ", category: "animals", english: "buffalo" },
  "𐔑𐔑": { bengali: "মহিষ", category: "animals", english: "water buffalo" },
  "𐔒𐔑": { bengali: "হাঁস", category: "animals", english: "duck" },
  "𐔓𐔑": { bengali: "মোরগ", category: "animals", english: "rooster" },
  "𐔔𐔑": { bengali: "হাতি", category: "animals", english: "elephant" },
  "𐔀𐔒𐔑": { bengali: "বাঘ", category: "animals", english: "tiger" },
  "𐔎𐔒𐔑": { bengali: "সিংহ", category: "animals", english: "lion" },
  "𐔋𐔒𐔑": { bengali: "খরগোশ", category: "animals", english: "rabbit" },
  "𐔍𐔒𐔑": { bengali: "ইঁদুর", category: "animals", english: "mouse" },
  "𐔏𐔒𐔑": { bengali: "পাখি", category: "animals", english: "bird" },
  "𐔐𐔒𐔑": { bengali: "মুরগি", category: "animals", english: "chicken" },
  "𐔑𐔒𐔑": { bengali: "ছাগল", category: "animals", english: "goat" },
  "𐔒𐔒𐔑": { bengali: "ভেড়া", category: "animals", english: "sheep" },
  "𐔓𐔒𐔑": { bengali: "শূকর", category: "animals", english: "pig" },
  "𐔔𐔒𐔑": { bengali: "উট", category: "animals", english: "camel" },
  "𐔀𐔓𐔑": { bengali: "বানর", category: "animals", english: "monkey" },
  "𐔎𐔓𐔑": { bengali: "কাঠবিড়ালি", category: "animals", english: "squirrel" },
  "𐔋𐔓𐔑": { bengali: "সাপ", category: "animals", english: "snake" },
  "𐔍𐔓𐔑": { bengali: "ব্যাঙ", category: "animals", english: "frog" },
  "𐔏𐔓𐔑": { bengali: "মাকড়সা", category: "animals", english: "spider" },

  // Feelings/Emotions (20 words)
  "𐔀𐔒": { bengali: "খুশি", category: "feelings", english: "happy" },
  "𐔎𐔒": { bengali: "দুঃখ", category: "feelings", english: "sad" },
  "𐔋𐔒": { bengali: "ভয়", category: "feelings", english: "fear" },
  "𐔍𐔒": { bengali: "রাগ", category: "feelings", english: "anger" },
  "𐔏𐔒": { bengali: "ভালবাসা", category: "feelings", english: "love" },
  "𐔐𐔒": { bengali: "উত্তেজনা", category: "feelings", english: "excitement" },
  "𐔑𐔒": { bengali: "নীরবতা", category: "feelings", english: "silence" },
  "𐔒𐔒": { bengali: "আশা", category: "feelings", english: "hope" },
  "𐔓𐔒": { bengali: "উদাসীনতা", category: "feelings", english: "indifference" },
  "𐔔𐔒": { bengali: "হতাশা", category: "feelings", english: "disappointment" },
  "𐔀𐔓𐔒": { bengali: "গর্ব", category: "feelings", english: "pride" },
  "𐔎𐔓𐔒": { bengali: "লজ্জা", category: "feelings", english: "shame" },
  "𐔋𐔓𐔒": { bengali: "ঈর্ষা", category: "feelings", english: "jealousy" },
  "𐔍𐔓𐔒": { bengali: "আনন্দ", category: "feelings", english: "joy" },
  "𐔏𐔓𐔒": { bengali: "চিন্তা", category: "feelings", english: "worry" },
  "𐔐𐔓𐔒": { bengali: "শান্তি", category: "feelings", english: "peace" },
  "𐔑𐔓𐔒": { bengali: "কৌতূহল", category: "feelings", english: "curiosity" },
  "𐔒𐔓𐔒": { bengali: "বিরক্তি", category: "feelings", english: "annoyance" },
  "𐔓𐔓𐔒": { bengali: "আত্মবিশ্বাস", category: "feelings", english: "confidence" },
  "𐔔𐔓𐔒": { bengali: "একাকীত্ব", category: "feelings", english: "loneliness" },

  // Time Words (15 words)
  "𐔀𐔑𐔃": { bengali: "সকাল", category: "time", english: "morning" },
  "𐔎𐔑𐔃": { bengali: "দুপুর", category: "time", english: "noon" },
  "𐔋𐔑𐔃": { bengali: "বিকেল", category: "time", english: "afternoon" },
  "𐔍𐔑𐔃": { bengali: "সন্ধ্যা", category: "time", english: "evening" },
  "𐔏𐔑𐔃": { bengali: "রাত", category: "time", english: "night" },
  "𐔐𐔑𐔃": { bengali: "ভোর", category: "time", english: "dawn" },
  "𐔑𐔑𐔃": { bengali: "আজ", category: "time", english: "today" },
  "𐔒𐔑𐔃": { bengali: "গতকাল", category: "time", english: "yesterday" },
  "𐔓𐔑𐔃": { bengali: "আগামীকাল", category: "time", english: "tomorrow" },
  "𐔔𐔑𐔃": { bengali: "সপ্তাহ", category: "time", english: "week" },
  "𐔀𐔒𐔃": { bengali: "মাস", category: "time", english: "month" },
  "𐔎𐔒𐔃": { bengali: "বছর", category: "time", english: "year" },
  "𐔋𐔒𐔃": { bengali: "ঘন্টা", category: "time", english: "hour" },
  "𐔍𐔒𐔃": { bengali: "মিনিট", category: "time", english: "minute" },
  "𐔏𐔒𐔃": { bengali: "সেকেন্ড", category: "time", english: "second" },

  // Environment (20 words)
  "𐔀𐔒𐔃": { bengali: "পাহাড়ি এলাকা", category: "environment", english: "mountainous area" },
  "𐔎𐔒𐔃": { bengali: "মাঠ", category: "environment", english: "field" },
  "𐔋𐔒𐔃": { bengali: "জঙ্গল", category: "environment", english: "forest" },
  "𐔍𐔒𐔃": { bengali: "নদীর তীরে", category: "environment", english: "river bank" },
  "𐔏𐔒𐔃": { bengali: "সাগরের তীরে", category: "environment", english: "seashore" },
  "𐔐𐔒𐔃": { bengali: "পুকুর", category: "environment", english: "pond" },
  "𐔑𐔒𐔃": { bengali: "গাছের নিচে", category: "environment", english: "under the tree" },
  "𐔒𐔒𐔃": { bengali: "পথ", category: "environment", english: "path" },
  "𐔓𐔒𐔃": { bengali: "বাজারের রাস্তা", category: "environment", english: "market street" },
  "𐔔𐔒𐔃": { bengali: "পাহাড়ের ধাপ", category: "environment", english: "mountain steps" },
  "𐔀𐔓𐔃": { bengali: "শহর", category: "environment", english: "city" },
  "𐔎𐔓𐔃": { bengali: "গ্রাম", category: "environment", english: "village" },
  "𐔋𐔓𐔃": { bengali: "রাস্তা", category: "environment", english: "road" },
  "𐔍𐔓𐔃": { bengali: "সেতু", category: "environment", english: "bridge" },
  "𐔏𐔓𐔃": { bengali: "পার্ক", category: "environment", english: "park" },
  "𐔐𐔓𐔃": { bengali: "উদ্যান", category: "environment", english: "garden" },
  "𐔑𐔓𐔃": { bengali: "চত্বর", category: "environment", english: "square" },
  "𐔒𐔓𐔃": { bengali: "গলি", category: "environment", english: "alley" },
  "𐔓𐔓𐔃": { bengali: "উঠান", category: "environment", english: "courtyard" },
  "𐔔𐔓𐔃": { bengali: "ছাদ", category: "environment", english: "roof" },

  // Miscellaneous (35 words)
  "𐔀𐔔𐔃": { bengali: "ভাল", category: "miscellaneous", english: "good" },
  "𐔎𐔔𐔃": { bengali: "খারাপ", category: "miscellaneous", english: "bad" },
  "𐔋𐔔𐔃": { bengali: "বড়", category: "miscellaneous", english: "big" },
  "𐔍𐔔𐔃": { bengali: "ছোট", category: "miscellaneous", english: "small" },
  "𐔏𐔔𐔃": { bengali: "দ্রুত", category: "miscellaneous", english: "fast" },
  "𐔐𐔔𐔃": { bengali: "ধীর", category: "miscellaneous", english: "slow" },
  "𐔑𐔔𐔃": { bengali: "গরম", category: "miscellaneous", english: "hot" },
  "𐔒𐔔𐔃": { bengali: "ঠান্ডা", category: "miscellaneous", english: "cold" },
  "𐔓𐔔𐔃": { bengali: "নতুন", category: "miscellaneous", english: "new" },
  "𐔔𐔔𐔃": { bengali: "পুরানো", category: "miscellaneous", english: "old" },
  "𐔀𐔀𐔃": { bengali: "হ্যাঁ", category: "miscellaneous", english: "yes" },
  "𐔎𐔀𐔃": { bengali: "না", category: "miscellaneous", english: "no" },
  "𐔋𐔀𐔃": { bengali: "সম্ভবত", category: "miscellaneous", english: "maybe" },
  "𐔍𐔀𐔃": { bengali: "অবশ্যই", category: "miscellaneous", english: "certainly" },
  "𐔏𐔀𐔃": { bengali: "এখানে", category: "miscellaneous", english: "here" },
  "𐔐𐔀𐔃": { bengali: "সেখানে", category: "miscellaneous", english: "there" },
  "𐔑𐔀𐔃": { bengali: "কোথায়", category: "miscellaneous", english: "where" },
  "𐔒𐔀𐔃": { bengali: "কিভাবে", category: "miscellaneous", english: "how" },
  "𐔓𐔀𐔃": { bengali: "কেন", category: "miscellaneous", english: "why" },
  "𐔔𐔀𐔃": { bengali: "কখন", category: "miscellaneous", english: "when" },
  "𐔀𐔎𐔃": { bengali: "সবসময়", category: "miscellaneous", english: "always" },
  "𐔎𐔎𐔃": { bengali: "কখনো না", category: "miscellaneous", english: "never" },
  "𐔋𐔎𐔃": { bengali: "কখনো কখনো", category: "miscellaneous", english: "sometimes" },
  "𐔍𐔎𐔃": { bengali: "প্রায়ই", category: "miscellaneous", english: "often" },
  "𐔏𐔎𐔃": { bengali: "খুব", category: "miscellaneous", english: "very" },
  "𐔐𐔎𐔃": { bengali: "একটু", category: "miscellaneous", english: "a little" },
  "𐔑𐔎𐔃": { bengali: "অনেক", category: "miscellaneous", english: "many/much" },
  "𐔒𐔎𐔃": { bengali: "কিছু", category: "miscellaneous", english: "some" },
  "𐔓𐔎𐔃": { bengali: "সব", category: "miscellaneous", english: "all" },
  "𐔔𐔎𐔃": { bengali: "কিছুই না", category: "miscellaneous", english: "nothing" },
  "𐔀𐔋𐔃": { bengali: "প্রথম", category: "miscellaneous", english: "first" },
  "𐔎𐔋𐔃": { bengali: "শেষ", category: "miscellaneous", english: "last" },
  "𐔋𐔋𐔃": { bengali: "মধ্যম", category: "miscellaneous", english: "middle" },
  "𐔍𐔋𐔃": { bengali: "পরবর্তী", category: "miscellaneous", english: "next" },
  "𐔏𐔋𐔃": { bengali: "আগের", category: "miscellaneous", english: "previous" }
};

// Grammar modifiers and special characters
const grammarModifiers = {
  "→past": "েছি", // past tense suffix
  "→fut": "ব", // future tense suffix  
  "→neg": "নি", // negative suffix
  "→cont": "ছি", // continuous suffix
  "→perf": "েছি", // perfect suffix
  "※": "জোর", // emphasis marker
  "⁂": "?" // question marker
};

// Create reverse mapping for Normal → Zerava
const normalToZerava = {};
for (let zerava in zeravaVocabulary) {
  const bengali = zeravaVocabulary[zerava].bengali;
  normalToZerava[bengali] = zerava;
}

// Add grammar modifiers to reverse mapping
for (let modifier in grammarModifiers) {
  normalToZerava[grammarModifiers[modifier]] = modifier;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { zeravaVocabulary, normalToZerava, grammarModifiers };
}